---

services:
  minio:
    image: $MINIO_IMAGE
    container_name: $MINIO_NAME
    ports:
      - "$API_PORT:9000"  # API
      - "$GUI_PORT:9001"  # Console UI
    environment:
      MINIO_ROOT_USER: $MINIO_USER
      MINIO_ROOT_PASSWORD: $MINIO_PASS
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  minio_data:
